server:
  port: 7771
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=false
    username: user
    password: FsZaBZtWx3RGEA2h
    driver-class-name: com.mysql.jdbc.Driver
  shardingsphere:
    sharding:
      default-database-strategy:
      tables:
mybatis:
  type-aliases-package: org.xr.user.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org.xr: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
pattern:
  name: 本地环境local